services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  commande-service:
    container_name: commande-service
    build: ./commande-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/commande
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    image: "commande-service-docker"
    depends_on:
      - mongo
    volumes:
      - mongodb_data:/data/db

  discoveryservice:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-service:8761/actuator/health"]
      interval: 10s

  mysqlprod:
    container_name: mysql-container
    ports:
      - "3306:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'productdb'
    volumes:
      - db:/var/lib/mysql

  backend_spring:
    build:
      context: ./ProduitService
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlprod:3306/productdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka

    ports:
      - "8091:8091"
    depends_on:
      - mysqlprod
    volumes:
      - ./backend_spring_data:/app/data

volumes:
  db:
  backend_spring_data:
  mongodb_data:

