services:
  discoveryservice:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-service:8761/actuator/health" ]
      interval: 10s

  esprit-salle-service:
    build: ./SalleService
    container_name: salle-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://salle-service:8084/actuator/health" ]
      interval: 10s
    depends_on:
      discoveryservice:
        condition: service_healthy


