version: '3.8'

services:
  mysqldbplant:
    container_name: plant-mysql-container
    ports:
      - "33067:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'PlantExercice'
    volumes:
      - /tmp

  esprit-plant-service:

    build: ./MicroServicePlantExercice
    container_name: plant-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysqldbplant


  gateway-service:
    build: ./api-gateway
    container_name: gateway-service
    ports:
      - '9191:9191'
    expose:
      - '9191'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway-service:9191/actuator/health"]
      interval: 10s
    depends_on:
      discoveryservice:
        condition: service_healthy

  mysqldb:
    container_name: exercice-mysql-container
    ports:
      - "33068:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'exercice'
    volumes:
      - /tmp

  esprit-exercice-service:
    build: ./Exercice
    container_name: exercice-service
    ports:
      - '8085:8085'
    expose:
      - '8085'

    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

    depends_on:
      - mysqldb

  discoveryservice:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-service:8761/actuator/health"]
      interval: 10s


  mysqlprod:
    container_name: mysql-container
    ports:
      - "33069:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'productdb'
    volumes:
      - /tmp

  backend_spring:
    build:
      context: ./ProduitService
      dockerfile: Dockerfile
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

    ports:
      - "8081:8081"


    healthcheck:
      test: [ "CMD", "curl", "-f", "http://coach-service:8082/actuator/health" ]
      interval: 10s
    depends_on:
      - mysqlprod
    volumes:
      - /tmp
    restart: always

  coach-service:
    build: ./coach
    container_name: coach-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://coach-service:8082/actuator/health" ]
      interval: 10s
    depends_on:
      discoveryservice:
        condition: service_healthy

  esprit-salle-service:
    build: ./SalleService
    container_name: salle-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://salle-service:8084/actuator/health" ]
      interval: 10s
    depends_on:
      discoveryservice:
        condition: service_healthy


volumes:
  db:
  backend_spring_data:
