version: "3.8"

services:
  mysqldb:
    container_name: mysql-container
    ports:
      - "3306:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'productdb'
    volumes:
      - db:/var/lib/mysql


  backend_spring:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/productdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    volumes:
      - ./backend_spring_data:/app/data

volumes:
  db:
  backend_spring_data:

